[versions]
kotlin = "2.2.21"
coroutines = "1.10.2"

android-gradle = "8.13.2"

kover = "0.9.3"
dokka = "2.0.0"
binary-compatibility-validator = "0.18.1"
jreleaser = "1.21.0"

slf4j = "2.0.17"
logback = "1.5.21"

byte-buddy = "1.18.2"
objenesis = "3.4"
dexmaker = "2.28.6"

junit4 = "4.13.2"
junit = "5.14.1"

spotless = "8.1.0"

kotlinx-benchmark = "0.4.14"

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

kotlin-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "coroutines" }

dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }

kover = { module = "org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin", version.ref = "kover" }
binary-compatibility-validator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
jreleaser = { module = "org.jreleaser:jreleaser-gradle-plugin", version.ref = "jreleaser" }

junit4 = { module = "junit:junit", version.ref = "junit4" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }

slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

dexmaker = { module = "com.linkedin.dexmaker:dexmaker", version.ref = "dexmaker" }

objenesis = { module = "org.objenesis:objenesis", version.ref = "objenesis" }

byte-buddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byte-buddy" }
byte-buddy-agent = { module = "net.bytebuddy:byte-buddy-agent", version.ref = "byte-buddy" }

spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless"}

kotlinx-benchmark-runtime = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }

[plugins]
kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }
