name: All tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      matrix:
        java-version: [1.8, 10, 11, 12, 13, 14, 15, 16, 17]
        kotlin-version: [1.3.72, 1.4.32, 1.5.31, 1.6.0]
        kotlin-ir-enabled: [true, false]
        exclude:
          - kotlin-version: 1.3.72
            kotlin-ir-enabled: true
      # in case one JDK fails, we still want to see results from others
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ matrix.java-version }}-${{ matrix.kotlin-version }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.java-version }}-gradle-
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests with Gradle
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: test --stacktrace -Pkotlin.version=${{ matrix.kotlin-version }} -Pkotlin.ir.enabled=${{ matrix.kotlin-ir-enabled }}
  android-instrumented-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 28, 29 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ matrix.api-level }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.api-level }}-gradle-
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck

